Repository m88i/nexus-operator, pull requests merged in 2020-05, with the labels that each got.

#45 Change workflow event
  .github/workflows/nexus-operator-pr-checks.yml
Labels: bug

#42 Closes #37: Add very basic e2e test use case
  .github/workflows/example-workflow-e2e-yaml.txt
  .github/workflows/nexus-operator-pr-checks.yml
  Makefile
  go.sum
  hack/ci/install-oc-client.sh
  hack/run-e2e-test.sh
  test/e2e/main_test.go
  test/e2e/nexus_test.go
Labels: enhancement

#47 Closes #46: Adding OLM Integration Test to CI
  .github/workflows/nexus-operator-pr-checks.yml
  Makefile
  hack/ci/install-kind.sh
  hack/ci/operator-ensure-manifest.sh
  hack/ci/operator-olm-test.sh
  hack/ci/operator-olm-verify.sh
  hack/ci/operatorhubio-catalog.Dockerfile
  hack/ci/start-kind.sh
Labels: enhancement

#44 Fix #20: add TLS configuration support
  README.md
  deploy/crds/apps.m88i.io_nexus_crd.yaml
  docs/TLS.md
  docs/img/operator-hub.png
  docs/img/sonatype-nexus-crop.svg
  docs/img/sonatype-nexus.svg
  examples/nexus3-centos-tls-ingress.yaml
  examples/nexus3-centos-tls-route.yaml
  pkg/apis/apps/v1alpha1/nexus_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/cluster/kubernetes/ingress.go
  pkg/controller/nexus/nexus_controller.go
  pkg/controller/nexus/nexus_controller_test.go
  pkg/controller/nexus/resource/comparator.go
  pkg/controller/nexus/resource/deployment.go
  pkg/controller/nexus/resource/ingress.go
  pkg/controller/nexus/resource/ingress_test.go
  pkg/controller/nexus/resource/resources.go
  pkg/controller/nexus/resource/route.go
  pkg/controller/nexus/resource/route_test.go
Labels: enhancement

#43 Fix #40: allow the Operator to start on Openshift 3.x
  pkg/framework/controller_watcher.go
Labels: openshift

#49 Closes #48: Add e2e test to CI
  .github/workflows/nexus-operator-integration-checks.yml
  .gitignore
Labels: enhancement

#50 Remove unnecessary watch logic for secrets
  pkg/controller/nexus/nexus_controller.go
  pkg/controller/nexus/resource/resources.go
Labels: enhancement

#56 Renaming Package to not clash with certified operators
  deploy/olm-catalog/nexus-operator/nexus-operator.package.yaml
Labels: bug

#58 Add Table of Contents
  README.md
Labels: enhancement

#57 Rebranding OLM Package Name
  bundle.Dockerfile
  deploy/olm-catalog/nexus-operator/0.2.0/nexus-operator.v0.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/nexus-operator/manifests/nexus-operator.clusterserviceversion.yaml
  deploy/olm-catalog/nexus-operator/metadata/annotations.yaml
  deploy/olm-catalog/nexus-operator/nexus-operator-m88i.package.yaml
  deploy/olm-catalog/nexus-operator/nexus-operator-operatorsource.yaml
  deploy/olm-catalog/nexus-operator/nexus-operator.package.yaml
  hack/ci/operator-ensure-manifest.sh
  hack/ci/operator-olm-test.sh
  hack/ci/operator-olm-verify.sh
  hack/generate-manifests.sh
  hack/olm-integration.sh
Labels: bug

#63 update roles.yaml
  deploy/role.yaml
Labels: bug

#66 Running e2e with operator image and RBAC instead of local
  .github/workflows/nexus-operator-integration-checks.yml
  hack/ci/load-operator-image.sh
  hack/ci/operator-olm-test.sh
  hack/ci/start-kind.sh
  hack/go-build.sh
  hack/go-mod-env.sh
  hack/run-e2e-test.sh
Labels: CI :heavy_check_mark:, enhancement :crown:

#69 Upgrading to SDK 0.17.1 minor patch
  .github/workflows/nexus-operator-integration-checks.yml
  go.mod
  go.sum
  hack/generate-manifests.sh
Labels: enhancement :crown:

#70 Closes #3: Add an option to not generate a random password for admin users
  README.md
  deploy/crds/apps.m88i.io_nexus_crd.yaml
  deploy/olm-catalog/nexus-operator/0.3.0/apps.m88i.io_nexus_crd.yaml
  deploy/olm-catalog/nexus-operator/0.3.0/nexus-operator.v0.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/nexus-operator/manifests/apps.m88i.io_nexus_crd.yaml
  deploy/olm-catalog/nexus-operator/manifests/nexus-operator.clusterserviceversion.yaml
  examples/nexus3-centos-no-volume.yaml
  pkg/apis/apps/v1alpha1/nexus_types.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/nexus/resource/deployment.go
  pkg/controller/nexus/resource/deployment_test.go
Labels: enhancement :crown:

#72 Integrating with GolangCI Lint
  .github/ISSUE_TEMPLATE.md/bug_report.md
  .github/ISSUE_TEMPLATE.md/feature_request.md
  .github/workflows/example-workflow-e2e-yaml.txt
  .github/workflows/nexus-operator-integration-checks.yml
  CONTRIBUTING.md
  README.md
  deploy/crds/apps.m88i.io_nexus_crd.yaml
  deploy/olm-catalog/nexus-operator/0.3.0/apps.m88i.io_nexus_crd.yaml
  deploy/olm-catalog/nexus-operator/0.3.0/nexus-operator.v0.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/nexus-operator/manifests/apps.m88i.io_nexus_crd.yaml
  deploy/olm-catalog/nexus-operator/manifests/nexus-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  go.tools.mod
  go.tools.sum
  hack/go-lint.sh
  hack/go-test.sh
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/nexus/nexus_controller.go
  pkg/controller/nexus/resource/deployment.go
  pkg/controller/nexus/resource/resources.go
  pkg/controller/nexus/resource/route.go
  pkg/logger/logger.go
  test/e2e/nexus_test.go
Labels: CI :gear:

#71 Adding more introduction information
  README.md
Labels: documentation :book:

#74 Fix Ingress comparison
  pkg/controller/nexus/resource/comparator.go
Labels: bug :bug:

#78 Renaming ISSUE_TEMPLATE according to Github policy
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/nexus-operator-integration-checks.yml
Labels: documentation :book:

#79 Rewrite resource life cycle logic
  pkg/controller/nexus/nexus_controller.go
  pkg/controller/nexus/resource/comparator.go
  pkg/controller/nexus/resource/defaults.go
  pkg/controller/nexus/resource/deployment/deployment.go
  pkg/controller/nexus/resource/deployment/deployment_test.go
  pkg/controller/nexus/resource/deployment/manager.go
  pkg/controller/nexus/resource/deployment/service.go
  pkg/controller/nexus/resource/deployment/service_test.go
  pkg/controller/nexus/resource/meta/object.go
  pkg/controller/nexus/resource/networking/ingress.go
  pkg/controller/nexus/resource/networking/ingress_test.go
  pkg/controller/nexus/resource/networking/manager.go
  pkg/controller/nexus/resource/networking/route.go
  pkg/controller/nexus/resource/networking/route_test.go
  pkg/controller/nexus/resource/persistence/manager.go
  pkg/controller/nexus/resource/persistence/pvc.go
  pkg/controller/nexus/resource/persistence/pvc_test.go
  pkg/controller/nexus/resource/rbac/manager.go
  pkg/controller/nexus/resource/resources.go
  pkg/controller/nexus/resource/security/manager.go
  pkg/controller/nexus/resource/security/service_account.go
Labels: enhancement :crown:
