Repository m88i/nexus-operator, pull requests merged in 2020-11, with the labels that each got.

#185 Fixing NGINX Ingress reverse proxy
  controllers/nexus/resource/deployment/deployment.go
  controllers/nexus/resource/deployment/deployment_test.go
  controllers/nexus/resource/deployment/service.go
  controllers/nexus/resource/networking/ingress.go
  controllers/nexus/resource/networking/ingress_test.go
  controllers/nexus/resource/networking/legacy_ingress.go
  controllers/nexus/resource/networking/legacy_ingress_test.go
  controllers/nexus/resource/networking/manager_test.go
  controllers/nexus/resource/networking/route.go
  controllers/nexus/resource/networking/route_test.go
  main.go
Labels: bug :bug:

#187 Removing resource limits from manager Deployment
  bundle/manifests/nexus-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  nexus-operator.yaml
Labels: bug :bug:, openshift

#188 Re-add TLS doc
  docs/TLS.md
Labels: documentation :book:

#189 Fix #186 - Add Nexus finalizers to ClusterRole
  bundle/manifests/nexus-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/nexus_controller.go
  hack/generate-toc.sh
  hack/install.sh
  nexus-operator.yaml
Labels: bug :bug:
