Repository m88i/nexus-operator, pull requests merged in 2020-07, with the labels that each got.

#107 Allow the fake client to mock server API error responses
  codecov.yml
  go.mod
  pkg/controller/nexus/nexus_controller_test.go
  pkg/framework/controller_watcher_test.go
  pkg/test/client.go
  pkg/test/client_test.go
  pkg/util/error.go
Labels: testing :white_check_mark:

#108 Remove unnecessary hack
  pkg/test/client.go
  pkg/test/client_test.go
Labels: testing :white_check_mark:

#110 Refactor resource managers to return their struct, not the interface
  pkg/controller/nexus/nexus_controller.go
  pkg/controller/nexus/resource/deployment/manager.go
  pkg/controller/nexus/resource/deployment/manager_test.go
  pkg/controller/nexus/resource/interfaces.go
  pkg/controller/nexus/resource/networking/manager.go
  pkg/controller/nexus/resource/networking/manager_test.go
  pkg/controller/nexus/resource/persistence/manager.go
  pkg/controller/nexus/resource/persistence/manager_test.go
  pkg/controller/nexus/resource/resources.go
  pkg/controller/nexus/resource/security/manager.go
Labels: enhancement :crown:

#112 Remove unnecessary nil checks on unexposed methods
  pkg/controller/nexus/resource/networking/ingress.go
  pkg/controller/nexus/resource/networking/ingress_test.go
  pkg/controller/nexus/resource/networking/manager.go
  pkg/controller/nexus/resource/networking/route.go
  pkg/controller/nexus/resource/networking/route_test.go
  pkg/controller/nexus/resource/security/manager.go
Labels: enhancement :crown:

#113 Create Make target for pre-PR checks and push automation
  CONTRIBUTING.md
  Makefile
  hack/pr-prep.sh
  hack/run-e2e-test.sh
Labels: documentation :book:, testing :white_check_mark:

#115 Link the Operator SDK repository to the project's description
  README.md
Labels: documentation :book:

#117 Let incorrect usage of the exposed API panic
  codecov.yml
  pkg/controller/nexus/resource/deployment/manager.go
  pkg/controller/nexus/resource/deployment/manager_test.go
  pkg/controller/nexus/resource/networking/manager.go
  pkg/controller/nexus/resource/networking/manager_test.go
  pkg/controller/nexus/resource/persistence/manager.go
  pkg/controller/nexus/resource/persistence/manager_test.go
  pkg/controller/nexus/resource/security/manager.go
  pkg/controller/nexus/resource/security/manager_test.go
Labels: enhancement :crown:

#119 change codecov to use action
  .github/workflows/nexus-operator-integration-checks.yml
Labels: CI :gear:

#126 Closes #124 Changed the operator testing image with older version of …
  hack/ci/operator-olm-test.sh
Labels: CI :gear:, bug :bug:

#121 Improve hack scripts
  .github/workflows/nexus-operator-integration-checks.yml
  hack/ci/install-kind.sh
  hack/ci/install-operator-sdk.sh
  hack/ci/start-kind.sh
  hack/go-build.sh
  hack/go-vet.sh
Labels: CI :gear:, enhancement :crown:

#128 Exit with 0 on successful pushes
  hack/pr-prep.sh
Labels: bug :bug:

#123 Comment only when change in codecov report
  .github/workflows/nexus-operator-integration-checks.yml
  codecov.yml
Labels: CI :gear:

#130 Changed the operator testing image back to use the latest image
  hack/ci/operator-olm-test.sh
Labels: CI :gear:

#131 Update README file to add info on increasing the data packet size for…
  README.md
Labels: documentation :book:
