Repository m88i/nexus-operator, pull requests merged in 2020-06, with the labels that each got.

#81 Only assign UID if using the community image
  .github/workflows/nexus-operator-integration-checks.yml
  pkg/controller/nexus/resource/deployment/deployment.go
Labels: enhancement :crown:

#85 Update REAME with SCC changes
  README.md
Labels: documentation :book:

#90 Move resource managing interfaces to a separate package
  pkg/controller/nexus/nexus_controller.go
  pkg/controller/nexus/nexus_controller_test.go
  pkg/controller/nexus/resource/deployment/manager.go
  pkg/controller/nexus/resource/infra/interfaces.go
  pkg/controller/nexus/resource/networking/manager.go
  pkg/controller/nexus/resource/persistence/manager.go
  pkg/controller/nexus/resource/resources.go
  pkg/controller/nexus/resource/security/manager.go
Labels: enhancement :crown:

#87 Move validation/defaults logic to Resource Managers (fix #82)
  deploy/crds/apps.m88i.io_nexus_crd.yaml
  deploy/olm-catalog/nexus-operator/0.3.0/apps.m88i.io_nexus_crd.yaml
  deploy/olm-catalog/nexus-operator/0.3.0/nexus-operator.v0.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/nexus-operator/manifests/apps.m88i.io_nexus_crd.yaml
  deploy/olm-catalog/nexus-operator/manifests/nexus-operator.clusterserviceversion.yaml
  pkg/apis/apps/v1alpha1/nexus_types.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/cluster/kubernetes/ingress.go
  pkg/controller/nexus/nexus_controller.go
  pkg/controller/nexus/nexus_controller_test.go
  pkg/controller/nexus/resource/deployment/deployment.go
  pkg/controller/nexus/resource/deployment/deployment_test.go
  pkg/controller/nexus/resource/deployment/manager.go
  pkg/controller/nexus/resource/deployment/manager_test.go
  pkg/controller/nexus/resource/networking/manager.go
  pkg/controller/nexus/resource/networking/manager_test.go
  pkg/controller/nexus/resource/persistence/manager.go
  pkg/controller/nexus/resource/persistence/manager_test.go
  pkg/controller/nexus/resource/persistence/pvc.go
  pkg/controller/nexus/resource/persistence/pvc_test.go
  pkg/controller/nexus/resource/resources.go
  pkg/controller/nexus/resource/security/manager.go
  pkg/framework/controller_watcher_test.go
  pkg/test/client.go
Labels: enhancement :crown:

#88 Enable golint linter in golangci-lint
  .github/workflows/nexus-operator-integration-checks.yml
  pkg/test/client.go
Labels: CI :gear:

#91 upgraded operator-sdk to v0.18.1
  .github/workflows/nexus-operator-integration-checks.yml
  go.mod
  go.sum
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/test/controller_mocks.go
Labels: enhancement :crown:

#94 Changed the way to download golangci-lint to remove
  hack/go-lint.sh
Labels: CI :gear:

#95 Add the default Service Account to the Nexus CR
  pkg/controller/nexus/resource/security/manager.go
Labels: bug :bug:

#97 Allow the user to select the Pull Policy
  README.md
  deploy/crds/apps.m88i.io_nexus_crd.yaml
  deploy/olm-catalog/nexus-operator/0.3.0/apps.m88i.io_nexus_crd.yaml
  deploy/olm-catalog/nexus-operator/0.3.0/nexus-operator.v0.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/nexus-operator/manifests/apps.m88i.io_nexus_crd.yaml
  deploy/olm-catalog/nexus-operator/manifests/nexus-operator.clusterserviceversion.yaml
  pkg/apis/apps/v1alpha1/nexus_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/nexus/resource/deployment/deployment.go
  pkg/controller/nexus/resource/deployment/manager.go
  pkg/controller/nexus/resource/deployment/manager_test.go
Labels: enhancement :crown:

#98 Add Nexus3 health check using its own API endpoint
  pkg/controller/nexus/resource/deployment/deployment.go
Labels: enhancement :crown:

#96 Add networking E2E tests
  .github/workflows/nexus-operator-integration-checks.yml
  CONTRIBUTING.md
  hack/run-e2e-test.sh
  pkg/controller/nexus/resource/deployment/deployment.go
  pkg/controller/nexus/resource/deployment/deployment_test.go
  pkg/controller/nexus/resource/deployment/manager.go
  pkg/controller/nexus/resource/deployment/manager_test.go
  pkg/controller/nexus/resource/deployment/service.go
  test/e2e/nexus_test.go
  test/e2e/tester_test.go
Labels: documentation :book:, testing :white_check_mark:

#102 Improve install script to install nexus using latest available tags
  hack/install.sh
Labels: documentation :book:, enhancement :crown:

#103 Integrate PR CI Check with Codecov
  .github/workflows/nexus-operator-integration-checks.yml
  codecov.yml
Labels: CI :gear:, enhancement :crown:
