Repository m88i/nexus-operator, pull requests merged in 2020-08, with the labels that each got.

#135 Move default/validation logic to separate package
  pkg/cluster/kubernetes/ingress.go
  pkg/controller/nexus/nexus_controller.go
  pkg/controller/nexus/resource/deployment/deployment_test.go
  pkg/controller/nexus/resource/deployment/manager.go
  pkg/controller/nexus/resource/deployment/manager_test.go
  pkg/controller/nexus/resource/networking/manager.go
  pkg/controller/nexus/resource/networking/manager_test.go
  pkg/controller/nexus/resource/persistence/manager.go
  pkg/controller/nexus/resource/persistence/manager_test.go
  pkg/controller/nexus/resource/persistence/pvc_test.go
  pkg/controller/nexus/resource/security/manager.go
  pkg/controller/nexus/resource/security/manager_test.go
  pkg/controller/nexus/resource/validation/defaults.go
  pkg/controller/nexus/resource/validation/validation.go
  pkg/controller/nexus/resource/validation/validation_test.go
  pkg/util/validation.go
  test/e2e/nexus_test.go
Labels: enhancement :crown:

#138 Add custom comparator for Deployments
  pkg/controller/nexus/resource/deployment/deployment.go
  pkg/controller/nexus/resource/deployment/manager.go
  pkg/controller/nexus/resource/deployment/manager_test.go
  pkg/controller/nexus/resource/validation/defaults.go
Labels: bug :bug:

#120 Closes #5: Introducing integration with Nexus server deployed
  .github/workflows/nexus-operator-integration-checks.yml
  README.md
  codecov.yml
  deploy/crds/apps.m88i.io_nexus_crd.yaml
  deploy/olm-catalog/nexus-operator/0.3.0/apps.m88i.io_nexus_crd.yaml
  deploy/olm-catalog/nexus-operator/0.3.0/nexus-operator.v0.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/nexus-operator/manifests/apps.m88i.io_nexus_crd.yaml
  deploy/olm-catalog/nexus-operator/manifests/nexus-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/run-e2e-test.sh
  pkg/apis/apps/v1alpha1/nexus_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/nexus/nexus_controller.go
  pkg/controller/nexus/nexus_controller_test.go
  pkg/controller/nexus/resource/deployment/manager.go
  pkg/controller/nexus/resource/deployment/manager_test.go
  pkg/controller/nexus/resource/networking/manager.go
  pkg/controller/nexus/resource/networking/manager_test.go
  pkg/controller/nexus/resource/persistence/manager.go
  pkg/controller/nexus/resource/persistence/manager_test.go
  pkg/controller/nexus/resource/resources.go
  pkg/controller/nexus/resource/security/manager.go
  pkg/controller/nexus/resource/security/manager_test.go
  pkg/controller/nexus/resource/security/secret.go
  pkg/controller/nexus/server/nexus.go
  pkg/controller/nexus/server/nexus_test.go
  pkg/controller/nexus/server/repositories.go
  pkg/controller/nexus/server/repositories_test.go
  pkg/controller/nexus/server/users.go
  pkg/controller/nexus/server/users_test.go
  pkg/framework/comparator.go
  pkg/framework/comparator_test.go
  pkg/framework/controller_watcher_test.go
  pkg/framework/fetcher.go
  pkg/framework/fetcher_test.go
  pkg/framework/types.go
  pkg/test/controller_mocks.go
  test/e2e/tester_test.go
Labels: enhancement :crown:

#145 Change references to 'main' branch
  .github/workflows/nexus-operator-integration-checks.yml
  README.md
  deploy/olm-catalog/nexus-operator/0.3.0/nexus-operator.v0.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/nexus-operator/manifests/nexus-operator.clusterserviceversion.yaml
  hack/ci/operatorhubio-catalog.Dockerfile
Labels: documentation :book:
