Repository m88i/nexus-operator, pull requests merged in 2020-10, with the labels that each got.

#168 Remove deprecated commands from github actions workflow
  .github/workflows/nexus-operator-integration-checks.yml
Labels: CI :gear:, Hacktoberfest, hacktoberfest-accepted

#172 Add goimports to hack/go-fmt.go
  hack/go-fmt.sh
  pkg/cluster/kubernetes/events.go
  pkg/cluster/kubernetes/events_test.go
  pkg/controller/nexus/nexus_controller_test.go
  pkg/controller/nexus/resource/deployment/manager.go
  pkg/controller/nexus/resource/validation/events_test.go
  pkg/controller/nexus/resource/validation/validation.go
  pkg/controller/nexus/update/events_test.go
  pkg/controller/nexus/update/monitor.go
  pkg/controller/nexus/update/monitor_test.go
  pkg/controller/nexus/update/tags.go
  pkg/controller/nexus/update/tags_test.go
  pkg/test/utils.go
Labels: Hacktoberfest

#166 Fixes #161,#157,#154: Cluster scoped operator
  .github/workflows/nexus-operator-integration-checks.yml
  .gitignore
  README.md
  RELEASE_NOTES.md
  cmd/manager/main.go
  deploy/namespace.yaml
  deploy/olm-catalog/nexus-operator/0.4.0/nexus-operator.v0.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/nexus-operator/manifests/nexus-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  hack/generate-manifests.sh
  hack/generate-yaml-installer.sh
  hack/install.sh
  hack/run-e2e-test.sh
  nexus-operator.yaml
  pkg/controller/nexus/resource/deployment/service.go
  pkg/controller/nexus/resource/deployment/service_test.go
  pkg/controller/nexus/server/nexus.go
  pkg/controller/nexus/server/nexus_test.go
  pkg/framework/controller_watcher.go
  test/e2e/nexus_test.go
  test/e2e/tester_test.go
Labels: Hacktoberfest, hacktoberfest-accepted

#176 Upgrade golangci-lint action
  .github/workflows/nexus-operator-integration-checks.yaml
Labels: CI :gear:, Hacktoberfest, security :bangbang:

#181 Move discovery to a separate package
  Makefile
  controllers/nexus/resource/networking/manager.go
  controllers/nexus/resource/networking/manager_test.go
  controllers/nexus/resource/resources.go
  controllers/nexus/resource/validation/validation.go
  controllers/nexus/resource/validation/validation_test.go
  controllers/nexus/update/tags.go
  controllers/nexus_controller.go
  controllers/suite_test.go
  main.go
  pkg/cluster/discovery/discovery.go
  pkg/cluster/discovery/discovery_test.go
  pkg/cluster/discovery/kubernetes.go
  pkg/cluster/discovery/kubernetes_test.go
  pkg/cluster/discovery/openshift.go
  pkg/cluster/discovery/openshift_test.go
  pkg/cluster/kubernetes/ingress.go
  pkg/cluster/openshift/routes.go
  pkg/test/client_test.go
Labels: enhancement :crown:

#184 Automate TOC generation
  Makefile
  README.md
  hack/generate-toc.sh
Labels: Hacktoberfest, documentation :book:
